---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: softserve-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: softserve-demo
  template:
    metadata:
      labels:
        app: softserve-demo
    spec:
      containers:
      - name: softserve-demo
        image: 584934534486.dkr.ecr.us-east-1.amazonaws.com/softserve-demo:lastest
        ports:
        - name: web
          containerPort: 8000
        resources:
          requests:
            memory: 256Mi
            cpu: 250m
          limits:
            memory: 256Mi
            cpu: 250m
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - general
      # tolerations:
      # - key: team
      #   operator: Equal
      #   value: devops
      #   effect: NoSchedule
